### ISSUE TITLE
Local actions enforces sudo

### ISSUE THREAD

**Issue by Guibod** [basho-labs/ansible-riak#49]
In `basho-labs.riak-kv/tasks/Debian.yml`
```yml

- name: Fetch ansible ansible_version
  local_action: shell ansible --version
  register: ans_ver

```

Should be:

```yml

- name: Fetch ansible ansible_version
  local_action: shell ansible --version
  register: ans_ver
  sudo: False

```

Because it will trigger a local sudo that is not mandatory. As it is not mandatory, it should explicitely ignore rights escalation (see: https://github.com/ansible/ansible/issues/1415#issuecomment-9726783 )

This is require for me since I moved from `sudo` to `become`/`become_user`
